spring:
  application:
    name: legal-system-modular
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml


  mail:
    host: smtp.gmail.com
    port: 587
    username: java92850@gmail.com
    password: inpukygtkqjhxyad
  servlet:
    multipart:
      max-file-size: 10MB



  cache:
    type: caffeine
    cache-names: currency
    caffeine:
      spec: maximumSize=1,expireAfterWrite=10m


legal:
  system:
    upload:
      image:
        directory:
          path: G:/uploads/


jwt:
  secret:  YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo
  expiration: 600000

server:
  port: 8087
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example  legalsystem: DEBUG



