spring:
  application:
    name: rest
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: java92850@gmail.com
    password: inpukygtkqjhxyad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

legal:
  system:
    upload:
      image:
        directory:
          path: G:/uploads/


jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo
  expiration: 600000

server:
  port: 8085
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example  legalsystem: DEBUG



