spring:
  application:
    name: legal-system-modular
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: java92850@gmail.com
    password: inpukygtkqjhxyad
  servlet:
    multipart:
      max-file-size: 10MB


server:
  port: 8084

legal:
  system:
    upload:
      image:
        directory:
          path: G:/uploads/

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3




  level:
    root: INFO
    liquibase: DEBUG
    org.springframework.jdbc.core: TRACE
    org.hibernate.SQL: DEBUG
    com.example.legalsystem.controller: DEBUG